# Generated by Django 5.0.3 on 2024-04-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], max_length=10)),
                ('potencia', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=10)),
                ('uso', models.CharField(choices=[('Esporádico', 'Esporádico'), ('Regular', 'Regular'), ('Frecuente', 'Frecuente'), ('Muy frecuente', 'Muy frecuente')], max_length=15)),
                ('zona', models.CharField(choices=[('Rural', 'Rural'), ('Urbano', 'Urbano'), ('Semi-Urbano', 'Semi-Urbano')], max_length=12)),
                ('salida', models.CharField(choices=[('Deportiva', 'Deportiva'), ('Doble propósito', 'Doble propósito'), ('Trabajo', 'Trabajo')], max_length=15)),
            ],
        ),
    ]
